### ISSUE TITLE
Unable to access documentation

### ISSUE THREAD

**Issue by karneaud** [omniship/omniship#1]
### Your Environment

- OS and Version: Docker Linux
- PHP Version: 7.3.x
- Omniship Version: #.#.#

### Expected behaviour

Should be able to access documentation

### Actual behaviour

website not found

### Steps to reproduce

go to https://omniship.werxe.com/

**Comment by brunogaspar** [comment]
It's not in a usable state.

**Comment by karneaud** [comment]
@brunogaspar are we talking about the website or the library? Any insights on what can be done...maybe I can help I note a similar package done by @cjario https://github.com/cjario/omniship-common
